Repository TalismanSociety/talisman-web, pull requests merged in 2025-05, with the labels that each got.

#1317 fix: assethub assets swaps
  apps/portal/src/components/widgets/swap/swap-modules/chainflip.swap-module.ts
  apps/portal/src/components/widgets/swap/swap-modules/common.swap-module.ts
  apps/portal/src/components/widgets/swap/swap-modules/simpleswap-swap-module.ts
  apps/portal/src/hooks/useSubstrateBalance.ts
  apps/portal/src/hooks/useSubstrateToken.ts
Labels: QA todo

#1322 fix: get chains and tokens from local store
  apps/portal/package.json
  apps/portal/src/domains/balances/currency.ts
  apps/portal/src/domains/chains/recoils.ts
  yarn.lock
Labels: bug

#1327 fix: swaps show all minimums
  apps/portal/src/components/widgets/swap/side-panel/SwapDetails.tsx
  apps/portal/src/components/widgets/swap/side-panel/details/SwapDetailsError.tsx
  apps/portal/src/components/widgets/swap/swap-modules/stealthex-swap-module.ts
Labels: QA todo

#1328 feat: display validators rewards by netuid
  apps/portal/src/components/widgets/staking/subtensor/DelegateSelectorDialog.tsx
  apps/portal/src/components/widgets/staking/subtensor/StakeSideSheet.tsx
  apps/portal/src/components/widgets/staking/subtensor/SubnetSelectorDialog.tsx
  apps/portal/src/components/widgets/staking/subtensor/SubtensorStakingForm.tsx
  apps/portal/src/domains/staking/subtensor/hooks/useCombinedBittensorValidatorsData.ts
Labels: QA pass
